# Set Variables

# Change ZSH Options

# Aliases
alias l="exa -lah --git"
alias nv="nvim"
alias rm="trash -rf"
alias tree="exa --tree --level=2"
alias bbd="brew bundle dump --force --describe"
alias man="batman"
alias grep="batgrep"
alias trail="<<<${(F)path}"
alias cat="bat"


# Add Locations to $PATH Variable

# Write Handy Functions
function mkcd() {
  mkdir -p "$@" && cd "$_";
}

# Use ZSH Plugins

# ...and Other Surprises


export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
